[package]
name = "melodie"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
inkwell = { version = "0.6.0", features = ["llvm18-1"] }
